### ISSUE TITLE
The ability to change the request method for the license url

### ISSUE THREAD

**Issue by AhmedPro2013** [Palethorn/native-adaptive-streaming#108]
Some streams' license url's request method is GET, so i would like to have the abiliity to change the request method from POST to GET.

**Comment by Palethorn** [comment]
This could relate to clear key encryption, although I don's see why it would not work. Either way, the player library handles any license or key retrieval internaly. I don't really see the point in extending that behaviour but I'll just leave this open in case I get around it.

**Comment by Palethorn** [comment]
Not a reasonable request. No response from the OP, I don't see a valid use case for this.
