### ISSUE TITLE
Cannot add request headers

### ISSUE THREAD

**Issue by sitthajaid77** [Palethorn/native-adaptive-streaming#109]
I try to put header "Referer" in my request playback. But it doesn't appear in the request header from inspector.
Am I wrong configuration or missing something, can I have suggestion please.
Thank you
<img width="1372" alt="Screen Shot 2565-07-15 at 11 05 54" src="https://user-images.githubusercontent.com/22445538/179148624-86bccc74-17a9-4b62-8b66-7cd74db2bb00.png">

**Comment by Palethorn** [comment]
Refere is one of those headers that you can insert client side. See #47
