### ISSUE TITLE
How can i use this on html page ?

### ISSUE THREAD

**Issue by rsk1987** [Palethorn/native-adaptive-streaming#114]
Hello,
can anyone tell me how can i use this html page? or can i get js code ?

**Comment by Palethorn** [comment]
It isn't adapted for standalone embed. I might do a build variant for this someday. You can clone the project and try to modify it for the purpose. There aren't many twists I believe. The storage API is not compatible that I know of.

**Comment by Palethorn** [comment]
Here you go https://github.com/Palethorn/nas-player-embed/releases/tag/v1.0.0. It's missing some features, I'll add them when I have the time.
