### ISSUE TITLE
video palying but only sounds comes out

### ISSUE THREAD

**Issue by spidy2356** [Palethorn/native-adaptive-streaming#115]
https://assets-1.entertainvideo.com/assets/media/59967d9e4d0d079f3eddf6a1a1b13a37/dash/59967d9e4d0d079f3eddf6a1a1b13a37.mpd
try to play this link but only sound comes and pictures not showing.
#bug

**Comment by Palethorn** [comment]
URL is invalid. Closing.

**Comment by spidy2356** [comment]
@Palethorn when I created the issue then the link was valid. Now the service is gone. So there is no way without close it. Thank you
