### ISSUE TITLE
Referer and User Agent on link

### ISSUE THREAD

**Issue by piratamovil** [Palethorn/native-adaptive-streaming#24]
Is there any way that Referrer or User Agent can be added to play the m3u8 links?

**Comment by Palethorn** [comment]
In the request headers or otherwise?

**Comment by Palethorn** [comment]
HLS.js seems to support a trick for what you might be asking:

```
xhrSetup: async (xhr, url) => {
   const accessToken = await getAccessToken()
   xhr.open('GET', url, true);
   xhr.setRequestHeader('Authorization', `Bearer ${accessToken}`)
}
```

**Comment by Palethorn** [comment]
Those headers are unsafe and restricted. They cannot be modified programmatically.
