### ISSUE TITLE
Is there a way to get   license URL from the URL itself for dash videos?

### ISSUE THREAD

**Issue by agk4444** [Palethorn/native-adaptive-streaming#39]
The idea is to append license URL to mpd URL separated by # tag

**Comment by Palethorn** [comment]
Since the # is used to separate streaming URL from the extension URI, I'll need to figure out another way to append the license URL, maybe sending an license URL as a urlencoded parameter
```
https://example.com/stream?la_url=https%3A%2F%2Fexample.com%2Flicense
```

**Comment by agk4444** [comment]
What I tried is adding the second hashtag for la_url but  Your way may work better

**Comment by Palethorn** [comment]
Extension now streamingurl#license_url format, so if you have some kind of formatted playlist or whatever, it's easier to load.
