### ISSUE TITLE
Dead link on README

### ISSUE THREAD

**Issue by slrslr** [Palethorn/native-adaptive-streaming#40]
Link under "mozilla addons" on https://github.com/Palethorn/native-adaptive-streaming/blob/master/README.md link to a no longer available page.

**Comment by Palethorn** [comment]
Thanks for reporting. I've been having some trouble publishing this extension to AMO. I hope to resolve it soon.

**Comment by Palethorn** [comment]
AMO published the extension, so far no problems.
