### ISSUE TITLE
how to get the url license from FlixOle.com

### ISSUE THREAD

**Issue by Superhackman** [Palethorn/native-adaptive-streaming#44]
how to get the url license from FlixOle.com to play a movie https://ver.flixole.com/watch/4b580231-5171-4550-8047-6d06b964e719 with this player

I have access to the url of the manifesto but this website uses magine and I do not understand how to obtain it, I have been experiencing according to the instructions to request the url license but it does not generate it to me https://tvoli.github.io/

**Comment by Palethorn** [comment]
Sorry, your question is out of scope. It's assumed that you already posses streaming URL and license URL that works.

**Comment by Superhackman** [comment]
@Palethorn the license url asks me token, so it doesn't work for me
