### ISSUE TITLE
Vivaldi browser issue

### ISSUE THREAD

**Issue by PDXsailor** [Palethorn/native-adaptive-streaming#45]
I am using Vivaldi 2.8.1664.40 (Stable channel) (64-bit) on a Razer Blade running Linux Mint 19.2. I tried to watch the pilot episode of Emergence on https://abc.go.com/emergence but got an error message for the codec not being there. I installed your extension, and enabled it for private browsing with no other extensions enabled, but it still didn't work. I also tried the other 2 extensions, and they didn't work either. When I tried Firefox with your extension it worked fine. I conclude there is something not right in Vivaldi that these extensions don't work, but thought you might be the place to start for homing in on the problem.Thanks

**Comment by Palethorn** [comment]
You could try following these instructions https://help.vivaldi.com/article/html5-proprietary-media-on-linux/, but it doesn't guarantee that it would work because Vivaldi isn't listed as supported on abc site https://support.abc.com/hc/en-us/articles/360024948532-Which-Web-browsers-are-supported-.
