### ISSUE TITLE
Options dialog broken in Chrome

### ISSUE THREAD

**Issue by cethomasson** [Palethorn/native-adaptive-streaming#46]
The options dialog is broken in Chrome.  None of the fields populate.  The extension error log reports that the function clearNode() is not defined.

I fixed locally by moving clearNode() function from globals.js to a new file utils.js, and then adding the new utils.js script to the head.html, index.html, and options.html file. Moving is needed because declaring var state_machine causes another error when included in options.html and the options dialog executes.

There's also a typo in options.js.  The clearNode() call in ajax2.get() needs to clear '#hlsjsSel'.  It currently clears '#dashjsSel' instead.

**Comment by Palethorn** [comment]
I'll look into it.
