### ISSUE TITLE
[Feature Request] add option to play best quality source

### ISSUE THREAD

**Issue by ivysrono** [Palethorn/native-adaptive-streaming#48]
From:
`https://tv.cctv.com/2017/05/12/VIDEfS2Zc1W0kNhH5ulNJuMc170512.shtml`
get:
`https://newcntv.qcloudcdn.com/asp/hls/main/0303000a/3/default/c854edd30134440abc760e38cea0818f/main.m3u8`
![图片](https://user-images.githubusercontent.com/2649544/74582173-43b7fd00-4ff3-11ea-8b72-2ade1cc0a667.png)
We want to auto play `576` directly.

**Comment by Palethorn** [comment]
Not sure what you want here? You want the extension to parse a html file and extract streaming url? Sorry, that's out of scope for the project.

**Comment by Palethorn** [comment]
If you want the extension to select the largest quality, I can add an option to extension settings for that. Please note that Auto option is the best as a default option because of the varying nature of internet download speeds for different users.

**Comment by ivysrono** [comment]
> 
> 
> If you want the extension to select the largest quality, I can add an option to extension settings for that. Please note that Auto option is the best as a default option because of the varying nature of internet download speeds for different users.

Yes, I want the option.

**Comment by Palethorn** [comment]
OK, that seems reasonable.

**Comment by Palethorn** [comment]
dash.js changed it's API, the adapter is broken. I still have some work to do.

**Comment by Palethorn** [comment]
Setting is under Options page of the extension. Please not that when this setting is active, selecting manually any of the qualities will disable the setting until reload.

![Screenshot_20200714_090019](https://user-images.githubusercontent.com/671689/87394912-bc29e680-c5b0-11ea-8674-bd1a777c5da1.png)
