### ISSUE TITLE
Add possibility to play HLS clips in H265 codec

### ISSUE THREAD

**Issue by yorliuk** [Palethorn/native-adaptive-streaming#50]
Need to add possibility to playback HLS clips encoded by H265 codec.
Currently, playback of this clips displaying only black screen and audio.

**Comment by Palethorn** [comment]
HEVC/H265 will be playable with this extension when this table shows that it's supported on Firefox and Chrome https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#HEVC_H.265
