### ISSUE TITLE
Empty settings hls.js and dash.js

### ISSUE THREAD

**Issue by AlexBelz** [Palethorn/native-adaptive-streaming#51]
Hello, I see empty settings (see below). Is it normal ? Else, How to correct this ?
![Capture](https://user-images.githubusercontent.com/55029991/76067129-28effd00-5f8f-11ea-9f8f-7a07ec75ba2c.JPG)

**Comment by Palethorn** [comment]
It's a bug, I'll look into it. Also reported here #46.

**Comment by AlexBelz** [comment]
Thank you @Palethorn !
