### ISSUE TITLE
Subtitle link needs to be added x2 before working

### ISSUE THREAD

**Issue by SNAPflix** [Palethorn/native-adaptive-streaming#54]
Hi!
First of all I'd like to say THAnk YOU for this extension!
I have ONE small issue with it that I find a bit annoying and would like to request for you to take a look at.

Every time I add a link to  a vtt file with subtitles, the extension restarts the video at first, then it needs to be added a second time before the extension shows the subtitles.
I hope you can fix this little bug.?

The browser I mostly use is either Firefox or "Kiwi browser" which is a fork of Firefox for Android devices. Please keep up your GOOD work, it's MUCH appreciated!

Thanks in advance!

**Comment by Palethorn** [comment]
Thank you for the report. I'll try and fix that. Same issue happens with the license url for DRM protected streams.
