### ISSUE TITLE
Video Player time slider Fix

### ISSUE THREAD

**Issue by paradox109** [Palethorn/native-adaptive-streaming#55]
We need a change for Video Player time slider. The problem is that the bubble is too big and the middle of it, doesn't actually represent the timestamp. You have to guess every time where to click to past forward for let's say 10 seconds and is really hard because you keep going forward or backwards. 

Hope i explained it, still think it's one of the best extention for hls players.

**Comment by Palethorn** [comment]
I understand. I'll try and fix that. And add 5 sec backward and forward controls.

**Comment by SlazE888** [comment]
time slider completely broken for all my HLS-streams from now. How i can downgrade version to last week version? please fix

**Comment by Palethorn** [comment]
Hello, are you referring to version 3.2.0 installed from [AMO](https://addons.mozilla.org). Can you describe how exactly is it broken. 
- Does it appear? 
- Does it not update? 
- Is it frozen in place? 
- Does it misrepresent the current time?
- Is the stream VOD or live?

I tested it just now and it seems that it works just fine.

**Comment by SlazE888** [comment]
Hello,
it even doesn't appear on all of my Live streams! On VOD it works well. I'm on Win-7-Ultimate_64bit. PLease fix.

**Comment by Palethorn** [comment]
Hello, currently the extension does not detect if live stream has DVR enabled. Seek bar that was appearing on live stream in earlier versions was a bug. This could be an improvement but it's not broken. I'll submit a new ticket for this request.

**Comment by SlazE888** [comment]
> Hello, currently the extension does not detect if live stream has DVR enabled. Seek bar that was appearing on live stream in earlier versions was a bug. This could be an improvement but it's not broken. I'll submit a new ticket for this request.

please I humbly ask for help. I would be very grateful, i'm so addicted to DVR seek bar for years ((( be so kind
p.s. Issue also persist and on latest Win-10 build. Good luck.

**Comment by Palethorn** [comment]
Follow this issue #59.
