### ISSUE TITLE
Header request to license url

### ISSUE THREAD

**Issue by okidokios** [Palethorn/native-adaptive-streaming#56]
Hello it is possible to add header request to the license url before I could stream dash with license url, the license url had a token, but they changed and add the token to header request so I try to add the authorization header but the header goes to the mpd and not the license url it is possible to add it to license url please also I know has been requested before but if you can add second audio option and if you need an example url I can supply one. Thank you the extension is awesome!

**Comment by Palethorn** [comment]
Hello, I understand the issue. I'll see what I can do. License request is handled using 3rd party underlying libraries so I need to check the documentation to see if I can add headers.

**Comment by okidokios** [comment]
Thanks hope you can add it will be cool :D

**Comment by Palethorn** [comment]
OK, I've included the custom headers in license request also. Please wait for the official release.

**Comment by AhmedPro2013** [comment]
Please release the extension with that feature! I need it!
