### ISSUE TITLE
Extension not available on Chrome Web Store?

### ISSUE THREAD

**Issue by nattofriends** [Palethorn/native-adaptive-streaming#57]
The link to the Chrome Web Store listing for the extension is a 404 right now, what happened to the listing?

**Comment by Palethorn** [comment]
I accidentally unpublished the item yesterday while trying to resolve an issue with the listing, and there is no way to publish it again until it passes a review. I believe it should be available again soon with the new version in place.

**Comment by Palethorn** [comment]
You can load the stable version from releases until the official listing becomes available https://github.com/Palethorn/native-adaptive-streaming/releases/download/v3.1.0/native-adaptive-streaming.chrome-v3.1.0.zip

**Comment by Palethorn** [comment]
Extension is available at chrome store again https://chrome.google.com/webstore/detail/native-mpeg-dash-%2B-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn
