### ISSUE TITLE
Support Request: Extension didn't shows all segments on some MPEG-Dash (mpd) live stream urls.

### ISSUE THREAD

**Issue by SlazE888** [Palethorn/native-adaptive-streaming#64]
As you can see, this live stream example have six segments[ width="640"] but extension recognized only one of them:
 https://livesim.dashif.org/livesim/periods_60/continuous_1/testpic_2s/Manifest.mpd
And on this picture you can see one more live stream example where such issue happened:
 https://dl.dropbox.com/s/b82dbakgnbr1dve/.png
Please fix.

**Comment by Palethorn** [comment]
Test stream that you provided lists different selection streams it seems. Extension doesn't currently support those because the underlying library does not support it. You can check here https://reference.dashif.org/dash.js/v3.1.2/samples/dash-if-reference-player/index.html.
