### ISSUE TITLE
Question: About setting-"Allow opening files by links" in Goggle Chrome.

### ISSUE THREAD

**Issue by SlazE888** [Palethorn/native-adaptive-streaming#65]
Hello. What exactly doing the option-"**Allow opening local files by links**"[i'm talking about your app version from zip-file posted here: #57], which can be activated in Goggle Chrome settings of your extension? Do I need to activate this setting for regular use or not? Thanks.

**Comment by Palethorn** [comment]
I don't know which setting are you referring to. Can you post a screenshot?

**Comment by SlazE888** [comment]
> I don't know which setting are you referring to. Can you post a screenshot?
Have a look please(selected in red rectangle):
https://dl.dropbox.com/s/3dztyiwfeov452d/.jpg

**Comment by Palethorn** [comment]
I see. I haven't noticed that before. It's a permission added when you load unpacked extension. It means you loaded the extension in development mode, and it's required if you want to reflect changes made to the source code. Extensions installed from .crx packages or from chrome web store do not have that permission. I hope this answers your question. I should probably pack the releases into .crx instead in zip to avoid confusion.

**Comment by SlazE888** [comment]
> I see. I haven't noticed that before. It's a permission added when you load unpacked extension. It means you loaded the extension in development mode, and it's required if you want to reflect changes made to the source code. Extensions installed from .crx packages or from chrome web store do not have that permission. I hope this answers your question. I should probably pack the releases into .crx instead in zip to avoid confusion.

yeah. can you please post the link for downloading "v3.1.0.crx" ?

**Comment by Palethorn** [comment]
Grab the .crx from here https://github.com/Palethorn/native-adaptive-streaming/releases/tag/v3.3.0
