### ISSUE TITLE
Support Request: Volume resetting after each seeking on DASH/HLS VoD.

### ISSUE THREAD

**Issue by SlazE888** [Palethorn/native-adaptive-streaming#66]
Steps to reproduce:
1) Start to play this VoD:
 http://demo.unified-streaming.com/video/machete/machete.ism/machete.mpd
2) Set volume slider on 100%(or any other value not equal 50%).
3) Seek somewhere on control bar and you will see that volume slider from now placed on default value equal 50%.
Please fix. And why extension didn't store volume level specified by user, can you please add such opportunity?

**Comment by Palethorn** [comment]
OK, this will be fixed.
