### ISSUE TITLE
Add a download feature (for Mozilla, at least)

### ISSUE THREAD

**Issue by ninep9up** [Palethorn/native-adaptive-streaming#71]
Please add a download feature. I've tried all of the other extensions (like really) but none work for targeted m3u8 with ts fragments. One that work download just a fragment of a ts file. Others just don't detect a stream (like really?). I'm using a built-in VPN by Mozilla, so maybe that's a case, otherwise my ISP blocks everything, with hls-dl with youtube-dl isn't an option (yeah, I'm not that noobish).

**Comment by ninep9up** [comment]
You can fork it to private repo or whatever, just add this for the sake of humanity.

**Comment by ninep9up** [comment]
I mean, merging a bunch of files from cache isn't that hard, but these guys were probably scamming the shit of the system, before they learned to code.

**Comment by Palethorn** [comment]
Sorry, I have no plans to support this feature. Project is purely for playback and easy stream preview. Anyone is free to fork the repository and make any changes to the source code they see fit.
