### ISSUE TITLE
Native browser player... 

### ISSUE THREAD

**Issue by Smorvel** [Palethorn/native-adaptive-streaming#74]
I don't like the player in your extension, it is too slow, animation just makes me mad =) and when I do click on video I wanna pause\play it and not show\hide HUD... That's the reason why i still use Native HLS Playback... Can you use native player, or add a choose to settings, or at least make your player faster?

Also maybe make name of extension a little bit shorter? Because it look not to well in omnibox
![image](https://user-images.githubusercontent.com/19754243/93188364-2db51b00-f741-11ea-914e-835463258b87.png)

**Comment by Palethorn** [comment]
The player is as it is. I haven't figured out a name for this extension that is both and informative about what it is. Regardles, people seem to find it easier than I expected.
I have removed few of the dependencies as a part of optimization, and for ease of distribution. If you have any specific issues with performace please report a ticket. eg. "menu animation is terribly slow" or such.
