### ISSUE TITLE
Not compatible with any revisions of hls.js 1.x

### ISSUE THREAD

**Issue by chromer030** [Palethorn/native-adaptive-streaming#88]

**Comment by Palethorn** [comment]
I tested my sample stream with the most recent version, 1.1.4-0.canary, and it works fine. If you can provide more information, for example any error trace from the browser developer console, or the exact hls.js version, it would be much appreciated.

**Comment by chromer030** [comment]
I'm using chrome in Linux, and tried HLS 1.xx very much, in some cases it loaded the stream after some minutes, but HLS 0.15.0 loads it in seconds...
in chrome developer console while using HLS 1.xx there will be `HLS error`

OS : Arch Linux
Browser : Google Chrome 98.0.4758.80 (Always using latest version)
Last working HLS version : 0.15.0 alpha 2.0
Streams for test :
[ABC News](https://dai2.xumo.com/amagi_hls_data_xumo1212A-abcnews/CDN/master.m3u8)
[Welt TV](https://live2weltcms-lh.akamaihd.net/i/Live2WeltCMS_1@444563/master.m3u8) (Germany Geo-Blocked, Use VPN)

**Comment by chromer030** [comment]
And the long list of `t` and the stream that never loads with HLS 1.xx but with 0.15.0 or prior loads quickly.

![Screenshot_20220209_180723](https://user-images.githubusercontent.com/13361552/153212391-a85824f8-4e74-4ed4-b211-442c8cd87927.jpg)

**Comment by Palethorn** [comment]
Thank you for the additional info, I will check it out.
