### ISSUE TITLE
Support Request: HLS live stream starting without video.

### ISSUE THREAD

**Issue by SlazE888** [Palethorn/native-adaptive-streaming#89]
Hello, i got issue on HLS live stream like this: "**HEVC Main L5.0, yuv420p, 3840x2160**"
Google Chrome extension, after starting stream, shows it as "blank black box", I can hear only sound. Please fix.

**Comment by chromer030** [comment]
Is your HLS playable in mpv or VLC ?

**Comment by SlazE888** [comment]
> Is your HLS playable in mpv or VLC ?

Sure it playble in latest VLC.

**Comment by akay777** [comment]
@SlazE888 hi, I'm very new to this can you please tell me that how to run this project, I mainly need DASH live streaming.
A little help would be appreciated.

Regards.

**Comment by chromer030** [comment]
@akay777 , this is a browser extenstion which can easily play DASH or HLS streams within browser with lots of features like playback speed control , Quality setting , etc.

For chromium / chrome install it from Chrome Web Store --> https://chrome.google.com/webstore/detail/native-mpeg-dash-+-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn

For Firefox install it from addon center : https://addons.mozilla.org/en-US/firefox/addon/native-mpeg-dash-hls-playback/

**Comment by SlazE888** [comment]
> @SlazE888 hi, I'm very new to this can you please tell me that how to run this project, I mainly need DASH live streaming.
> A little help would be appreciated.
> 
> Regards.

Hi, read message above from @chromer030. :)

**Comment by Palethorn** [comment]
HEVC is iffy. I believe it's only properly supported in Edge at the moment. Haven't tested any yet. If the upstream developers support it, then this extension will support it as well. I tested newer versions of hls.js and there seem to be no issues at first glance.
Closing down.

**Comment by SlazE888** [comment]
> I believe it's only properly supported in Edge at the moment.

I try your extension[v4.0.0] in Edge and HLS(HEVC) live stream also starting without video there.
