### ISSUE TITLE
Question: What exactly these parameters doing?

### ISSUE THREAD

**Issue by SlazE888** [Palethorn/native-adaptive-streaming#96]
Hello,
what exactly, selected in green rectangles, parameters on picture bellow doing(if i watch adaptive stream with a few video tracks) and why it's disabled by default?
![Untitled](https://user-images.githubusercontent.com/53570520/139859047-a2ecbbed-d537-4900-bfb5-308fe808f2f2.png)

**Comment by Palethorn** [comment]
Hello,
- Automatically play videos at maximum quality - If the stream has multiple qualities (that means different resolution and different bitrates), and this options is enabled, player use the maximum quality available. Player will not automatically select stream quality based on your network speed.
- Maintain original video size - If enabled, the player will not stretch the video to browser window size, instead it will render it in native resolution.

**Comment by SlazE888** [comment]
> * Automatically play videos at maximum quality - If the stream has multiple qualities (that means different resolution and different bitrates), and this options is enabled, player use the maximum quality available. Player will not automatically select stream quality based on your network speed.
> * Maintain original video size - If enabled, the player will not stretch the video to browser window size, instead it will render it in native resolution.

Good day!
I thought so. Thanks for the reply. Welcome back @Palethorn !

**Comment by Palethorn** [comment]
> 
>Welcome back @Palethorn !
Thanks.
